apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources.yaml
  - aggregated-roles.yaml
namespace: kubeflow
patches:
  # Add securityContext to Spark Operator Pod.
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=spark-operator"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
